// src/core/components/FFormMain.tsx
import { h } from "tsx-dom"

import { Form } from '@/core'
import { ControlsContainer, GeneralMessageError } from '@/core'
import { FormModes } from "../form"

interface FMainAttributes {
  form: Form;
  slots?: {
    [k: string]: any
  }
}

export function FFormMain({ form, slots }: FMainAttributes) {
  const isCreateMode = form.settings.mode === FormModes.CREATE_MODE
  const filteredFields = Object.entries(form.fields).filter(([, field]) => {
    if (field.hidden) return false

    if (isCreateMode && !field.updateOnly) return true
    if (!isCreateMode && !field.createOnly) return true

    return false
  })

  const inputs = filteredFields.map(([fieldKey, field]) => {
    const hasBeforeField = slots && slots[`before-${fieldKey}`]
    const hasAfterField = slots && slots[`after-${fieldKey}`]
    
    const BeforeField = hasBeforeField ? slots[`before-${fieldKey}`] : () => undefined
    const AfterField = hasAfterField ? slots[`after-${fieldKey}`] : () => undefined
    
    const ControlGenerator = field.RenderField
    const input = (
      <ControlGenerator
        field={field}
        fieldKey={ fieldKey }
        { ...field }
      />
    )

    const controlContainer = [
      <BeforeField />,
      input,
      <AfterField />
    ]

    field.ref = input
    
    return controlContainer
  })

  const messageError = form.generalError ? <GeneralMessageError></GeneralMessageError> : undefined

  return (
    <ControlsContainer>
      { inputs }
      { messageError }
    </ControlsContainer>
  )
}

// src/forms/components/FFormMain.vue
<template>
  <main
    class="px-4 grid grid-cols-12 gap-x-8"
    v-bind="$attrs"
  >
    <template
      v-for="([fieldKey, field]) in fields"
      :key="fieldKey"
    >
      <slot :name="`before-${fieldKey}`" />
      <component
        :is="getComponent(field)"
        v-bind="field"
        v-model="field.modelValue"
      />
      <slot :name="`after-${fieldKey}`" />
    </template>
  </main>
</template>

<script lang="ts" setup>
import type { Form, NormalizedFieldStructure } from '@/forms'
import { controls } from '@/settings'

const props = defineProps<{
  form: Form
}>()

const getComponent = (field: NormalizedFieldStructure) => {
  type ControlType = keyof typeof controls
  return controls[field.type as ControlType] || controls.text
}

const fields = computed(() => {
  const _fields = Object.entries(props.form.fields).filter(([_, field]) => {
    if (field.hidden)
      return false

    if (field.createOnly && props.form.settings.mode !== FormModes.CREATE_MODE)
      return false

    if (field.updateOnly && props.form.settings.mode === FormModes.CREATE_MODE)
      return false

    return true
  })

  return _fields
})

onMounted(() => getForeignKeys(props.form.fields))
</script>
